### PR TITLE
Experimental refactoring.

### PR DESCRIPTION
**Pull request by n0toose**
This really took me a ***LOT*** of time and looking carefully throughout the codebase at least 6 times, but please take my pull request with a grain of salt.

Here's a list of some of the things that I did:
- I fixed the comments in order to make them meet the criteria of the  [Coding Guidelines](https://www.haiku-os.org/development/coding-guidelines).
- I tried to break many things that took up a lot of columns into multiple lines, as described in the [Coding Guidelines](https://www.haiku-os.org/development/coding-guidelines). I ***did not completely do that*** on instances of dereferencing, because I was not sure how to do that. (You will probably be able to locate such instances by looking for the `->` characters in the files.)
- I reorganized the order of the header files.
- I put one blank line in between of in blocks.
- I tried to replace as many occasions of nested `if`'s inside of `else`'s as possible, unless if there was another small action (such as variable definition) in between of the two blocks.
- I broke certain strings between lines, *apart from the copyright notices in the `window.h` file*.
- I added spaces next to commas. A lot of them. Manually.

Since this is a codebase that's >2000 lines large and due to the time constraint, I'd like to politely request for an extra proofread before the merge of this pull request. I tried to do whatever I could possibly do on my own and tried to push my abilities to their limits, but if there are any further concerns regarding the changes or any small mistakes that I may have made, I'll be more than glad to listen to them or fix any errors that have arised.

There are no functional changes in the pull request.

### CODE REVIEW

**Comment by owenca** [comment]
As described in the GCI task, the main goal is to address Issue #7. Reformatting the code for our coding guidelines is optional, and we already have a [tool](https://github.com/owenca/haiku-format) that can do most of the work.

I suggest that you start with [window.h](https://github.com/HaikuArchives/Resourcer/blob/master/main/window.h). Move all function definitions to a new file` window.cp` and make necessary changes in other source files.

Then submit a new PR with _only the text files you added and changed_.

**Comment by owenca** [comment]
As described in the GCI task, the main goal is to address Issue #7. Reformatting the code for our coding guidelines is optional, and we have a [tool](https://github.com/owenca/haiku-format) that can do most of the work.

I suggest that you start with window.h and move all function definitions to a new file window.cp. Then submit a pull request that _only includes the text files you have added and changed_.

**Comment by n0toose** [comment]
Will do. Should've done more research.

Is there anything that can prove to be useful in my commits either way?

**Comment by Zotyamester** [comment]
I say this is a good start, but one of the main problems of the codebase (IMO) is that it puts actual code in header files which is a pretty ugly and anti-reusable thing to do. I've started to separate things, but it's a lot of work.

**Pull request closed without merging**
